# Generated by Django 5.0.4 on 2024-05-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_todo_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='desc',
        ),
        migrations.AddField(
            model_name='todo',
            name='body',
            field=models.TextField(blank=True, default='No body'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
